### ISSUE TITLE
Typing /re just shows Available commands, no UI comes up

### ISSUE THREAD

**Issue by emeria** [Nihilianth/REToolbox#2]
How do I get the UI to show?
When I type /re, nothing comes up. To install, I took the 4 folders from the zip and dropped them into my addons folder.

Typing /re show, the command wont submit and just sits there.

Hatch71 on discord is having the same issue - "I re-installed and cleared cache but since latest Ascension patch RETB no longer works. When I do /re show all I get message "[RETB: Not initialized yet." It is not possible to do only /re show , not possible to press enter after that.
Are there other players with same issue? Did I miss a memo?

Ah, just noted someone else put up the issue on github."

**Comment by Nihilianth** [comment]
Hey there. I haven't been playing for a while. Currently a bit busy but I will look into this issue on the weekend. Thanks for reporting.

**Comment by emeria** [comment]
Thanks! Hoping you can find a fix.
