### ISSUE TITLE
Updated Mystic Enchant UI release

### ISSUE THREAD

**Issue by andrew6180** [Nihilianth/REToolbox#3]
Unsure if this broke your addon but I would assume so. Some of the new stuff added might be very useful to your addon though.

you can get an enchants info with
```lua 
local spell_id = 0
local RE = GetREData(spell_id)
```
which contains 
```lua
enchantID = 0
class = "ANY" or "ARMOR"
spellID = 0
spellName = ""
quality = 2 to 5. Green / blue / purple / legendary
stackable = max stacks
requiredLevel = unused
known = true or false if known or not. (Only has a value after the player opens the enchant window. Use IsReforgeEnchantmentKnown(enchant_id))
```

The global name references for all of the frame elements were removed and its all now accessible under `AscensionUI.MysticEnchant`, `MysticEnchant` being the main / base frame.

Also the UI now colors RE tooltip names by quality.

**Comment by Nihilianth** [comment]
Thanks for the info. Implemented in new release
